### ISSUE TITLE
Villagers Still Infinitely Restock even After Removing Plugin.

### ISSUE THREAD

**Issue by paracxsm** [spartacus04/InstantRestock#4]
Hey. so I've noticed that even after I edit the config and remove the plugin, the villagers still manage to restock infinitely, is this an issue? Or am I able to fix this, Thanks!

**Comment by spartacus04** [comment]
Hi, have you tried enabling the uninstall mode in the config?
If it doesn't work, let me know

**Comment by spartacus04** [comment]
oh wait, i didn't notice you closed the issue already.
Did you manage to restore the villagers?
