### ISSUE TITLE
[FEATURE REQUEST]: Stackable Curing

### ISSUE THREAD

**Issue by Joko991** [spartacus04/InstantRestock#47]
### Describe the solution you'd like.

Sorry if this is not possible, but could you add a feature which adds back stackable trades to villagers? (MC-181190) I haven't been able to find a solution to this issue that isn't messy, but it's fine if this isn't the right place to ask.

**Comment by spartacus04** [comment]
Hello! thanks for the feature request unfortunately I do not plan to add this to the infinite villager trades plugin, however since the minecraft community is pretty divided about this bug fix I could try to make a separate plugin for it.

**Comment by spartacus04** [comment]
I actually speedrun making that plugin, you can check it out [here](https://github.com/spartacus04/StackableCuring). It's available for download on spigot, hangar, github and (soon) modrinth.
