### ISSUE TITLE
[Bug]: UnninstalMode does not work.

### ISSUE THREAD

**Issue by Kibaxmc** [spartacus04/InstantRestock#49]
### Describe the bug

Enabling unninstalmode is just broken. All villagers trades get locked. I tried waiting for 2 hours and the villagers wont restock at all. How do i fix this issue?

### Steps to reproduce

Yes

### Expected behaviour

I want them to go back to vannila way of trading. Like keep their trades but they can still run out like in vannila.

### Server Version

1.20.1

### Server Type

Paper

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by spartacus04** [comment]
Hello! I just tested this and the uninstall mode works in my environment. Perhaps the villager is not restocking the trades. Can the villager access their workstation?
