### ISSUE TITLE
[Bug]: Reloading the plugin resets uninstallMode config to false

### ISSUE THREAD

**Issue by EminGT** [spartacus04/InstantRestock#66]
### Describe the bug

I wanted to use the uninstallMode on my server to get rid of the instant restocking villagers, but I noticed that the uninstall feature keeps turning off. After some examination, doing "/instantrestock config uninstallMode true" sets the uninstallMode to true correctly, but doing "/instantrestock reload" or restarting the server resets the uninstallMode config to false.

### Steps to reproduce

1) do /instantrestock config uninstallMode true
2) do /instantrestock reload
3) see that uninstallMode is false now

### Expected behaviour

I would expect the uninstallMode to remain true after server restarts or plugin reloads

### Server Version

1.21

### Server Type

Paper

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.

**Comment by TheXoXoX** [comment]
I have the same problem. Tried any combination of commands / restarts, this plugin once activated cannot be disabled... which sucks because now every trader is locked at 64 emeralds with no way to turn it off. Help?
